---
galaxy_info:
  role_name: pki_manager
  author: Oriol Rius
  description: Manage X.509 certificates via PKI Manager API
  company: joor.net
  license: MIT
  min_ansible_version: "2.14"

  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Fedora
      versions:
        - "39"
        - "40"

  galaxy_tags:
    - pki
    - certificates
    - x509
    - ssl
    - tls
    - security
    - ca
    - certificate_authority

dependencies: []
